version: '3'
services:
  database:
    image: postgres:14.2-alpine
    environment:
      POSTGRES_PASSWORD: postgres_password
  redis:
    image: 'redis:latest'
  service:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - PGUSER=postgres
      - PGHOST=database
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  client:
    build:
      context: ./client-typescript
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./client-typescript:/app
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev

# remote
# username: postgres
# password: postgrespassword

# aws creds
# access_key: AKIASLPOQQM5USJYFQPE
# secret_access_key: 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