version: 2.1
orbs:
  node: circleci/node@5.0.2

jobs:
  build_client:
    docker:
      - image: cimg/base:2022.03
    steps:
      - checkout
      - setup_remote_docker:
          version: "20.10.11"
      - run:
          command: docker build -t vardhmanhundia/multi-client ./client-typescript
          name: build client image

  build_client_test:
    docker:
      - image: cimg/base:2022.03
    steps:
      - checkout
      - setup_remote_docker:
          version: "20.10.11"
      - run:
          command: docker build -t vardhmanhundia/react-test -f ./client-typescript/Dockerfile.dev ./client-typescript
          name: build test image for client-typescript
      - run:
          command: docker run vardhmanhundia/react-test npm run test
          name: run client-typescript tests

  hithere:
    executor:
      name: node/default
    steps:
      - checkout
      - run: echo "hi there"

workflows:
  version: 2
  test_client:
    jobs:
      - client_test
      - build_client:
          requires:
            - "client_test"
