version: 2.1
orbs:
  node: circleci/node@5.0.2

jobs:
  build_client:
    executor:
      name: node/default
      tag: 14.15.1
    steps:
      - checkout
      - run:
          command: docker build -t vardhmanhundia/multi-client ./client
          name: build client image

  client_test:
    executor:
      name: node/default
      tag: 14.15.1
    steps:
      - checkout
      - run:
          command: docker build -t vardhmanhundia/react-test -f ./client/Dockerfile.dev ./client
          name: build test image for client
      - run: docker run vardhmanhundia/react-test npm test -- --coverage

  hithere:
    executor:
      name: node/default
    steps:
      - checkout
      - run: echo "hi there"

workflows:
  version: 2
  test_client:
    jobs:
      - client_test
      - build_client:
          requires:
            - "client_test"
