version: 2.1
orbs:
  node: circleci/node@5.0.2

jobs:
  build_and_push_images:
    docker:
      - image: cimg/base:2022.03
    steps:
      - checkout
      - setup_remote_docker:
          version: "20.10.11"
      - run:
          command: docker build -t vardhmanhundia/multi-client ./client-typescript
          name: build client image
      - run:
          command: docker build -t vardhmanhundia/multi-nginx ./nginx
          name: build nginx image
      - run:
          command: docker build -t vardhmanhundia/multi-service ./server
          name: build service image
      - run:
          command: docker build -t vardhmanhundia/multi-worker ./worker
          name: build worker image
      - run:
          command: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
          name: docker login
      - run:
          command: docker push vardhmanhundia/multi-client
          name: push client image
      - run:
          command: docker push vardhmanhundia/multi-nginx
          name: push nginx image
      - run:
          command: docker push vardhmanhundia/multi-service
          name: push service image
      - run:
          command: docker push vardhmanhundia/multi-worker
          name: push worker image

  client_test:
    docker:
      - image: cimg/base:2022.03
    steps:
      - checkout
      - setup_remote_docker:
          version: "20.10.11"
      - run:
          command: docker build -t vardhmanhundia/react-test -f ./client-typescript/Dockerfile.dev ./client-typescript
          name: build test image for client-typescript
      - run:
          command: docker run vardhmanhundia/react-test npm test
          name: run client-typescript tests

  deploy:
    docker:
      - image: cimg/base:2022.03
    steps:
      - checkout
      - run:
          name: Installing deployment dependencies
          command: |
            sudo apt-get -y -qq update
            sudo apt-get install python3-pip python-dev build-essential
            sudo pip install --upgrade setuptools
            sudo pip install awsebcli --upgrade
      - run:
          name: Deploying to EB
          command: eb deploy "$EBENB"

  hithere:
    executor:
      name: node/default
    steps:
      - checkout
      - run: echo "hi there"

workflows:
  version: 2
  build:
    jobs:
      - build_and_push_images
      - deploy:
          requires:
            - build_and_push_images
          filters:
            branches:
              only:
                - final
